#!/bin/bash

start(){
	tc qdisc add dev bond0.70 root handle 1: cbq avpkt 1000 bandwidth 600mbit
	tc class add dev bond0.70 parent 1: classid 1:1 cbq rate 500mbit allot 1500 prio 5 bounded isolated
	tc filter add dev bond0.70 parent 1: protocol ip prio 16 u32 match ip dst 172.16.67.100 flowid 1:1
}

stop(){
	tc qdisc del dev bond0.70 root
}

case $1 in 
	"start") start
	;;
	"stop") stop
	;;
	*) echo "Diga stop ou start"
esac
